name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: 'Deploy to NuxtHub'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write
    # defaults:
    #   run:
    #     working-directory: /

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      # - name: Ensure NuxtHub module is installed
      #   run: yarn nuxthub@latest ensure

      - name: Build application
        run: yarn build

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1
        id: deploy
        with:
          project-key: maple-map-exp-oe05
          # directory: //dist
          directory: dist
